force-app/main/default/objects/SmartVideoSetting__mdt/fields/api_key__c.field-meta.xml
<CustomField>
    <fullName>api_key__c</fullName>
    <defaultValue>&quot;-&quot;</defaultValue>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmartVideoSetting__mdt/fields/environment__c.field-meta.xml
<CustomField>
    <fullName>environment__c</fullName>
    <defaultValue>&quot;generic&quot;</defaultValue>
    <label>Environment</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmartVideoSetting__mdt/fields/external_id__c.field-meta.xml
<CustomField>
    <fullName>external_id__c</fullName>
    <defaultValue>&quot;POC&quot;</defaultValue>
    <label>External ID</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SmartVideoSetting__mdt/fields/use_custom_permissions__c.field-meta.xml
<CustomField>
    <fullName>use_custom_permissions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Custom Permissions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SmartvideoSettingService.cls
public virtual class SmartvideoSettingService {
    /**
     * @description Retrieve settings from custom metadata type SmartVideoSetting__mdt object
     * @return SmartVideoSetting__mdt - A record containing the settings
     */
    public virtual SmartVideoSetting__mdt getSettings() {
        List<SmartVideoSetting__mdt> result = [
            SELECT api_key__c, environment__c, external_id__c, use_custom_permissions__c  FROM SmartVideoSetting__mdt LIMIT 1
        ];

        if (Test.isRunningTest()) {
            result.clear();
            result.add(
                new SmartVideoSetting__mdt(
                    environment__c = 'generic',
                    external_id__c = 'external-id-test-value',
                    api_key__c = 'api-key-test-value',
                    use_custom_permissions__c = false
                )
            );
        }

        if (result.IsEmpty()) {
            return null;
        }

        return result.get(0);
    }
}